### ISSUE TITLE
Task list test

### ISSUE THREAD

**Issue by mattbilan** [mattbilan/Swell-Spotter-Test#21]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] <span data-href="#aha_task_list_21/SS-513-1" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> Task 1
    As a \*actor\*, I need \*something to happen\*, so that \*outcome\*.

- [ ] <span data-href="#aha_task_list_21/SS-513-2" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> Task 2
    As a \*actor\*, I need \*something to happen\*, so that \*outcome\*.

- [ ] <span data-href="#aha_task_list_21/SS-513-3" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> Task 3
    Do the task
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://bilancorp.aha.io/features/SS-513
